version: "3.12.1"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    entrypoint: ["sh", "/app/entrypoint.sh"]